/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.veho;

import com.veho.controller.MeetingController;

public class App {
    public static void main(String[] args) throws Exception  {
     new MeetingController();
    }
}
