/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.veho;

import com.veho.controller.MeetingController;
import spark.Spark;

import java.util.HashMap;

public class App {
    public static void main(String[] args) throws Exception  {
     new MeetingController();
    }


}
